language:
  java

sudo:
  false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/google-cloud-sdk

services:
  - docker

install:
  skip

addons:
  sonarcloud:
    organization: "piggyback"

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-location
  - docker build -t piggy1/location .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push piggy1/location
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; gcloud components install docker-credential-gcr | bash; fi

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
