language: java

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  - "$HOME/google-cloud-sdk"

services:
- docker

before_install:
- openssl aes-256-cbc -k "$DECRYPT_KEY" -in secret-storage.json.enc -out secret-storage.json -d -md sha256

install: skip

addons:
  sonarcloud:
    organization: piggyback

script:
- mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-location
- docker build -t piggy1/location .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push piggy1/location
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- mvn -Pprod clean verify
- docker build -t location-prod .
- docker tag location-prod gcr.io/absolute-text-251105/piggy1-location:v1
- cat secret-storage.json | docker login -u _json_key --password-stdin https://gcr.io
- docker push gcr.io/absolute-text-251105/piggy1-location:v1

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: lxfKeIcRTJ1e+Cw5Lo11qy8klwUfx/K1X1H4umq/hfhEOLoLRFmiqmRn1QK8vNguDOR9VHMP0sh87K82akIPhigDyJvzvxsbqzx+pMnQ0VIrzlPI//MUiw77sN6shayoIRF2/aQbg2jEWGOjt/UpR8sGzv73lTeVGfvIiMNdpigDhudcCTaRKFGAklnruIVUP9J46dVzDtA1w2fd6B5k2xs8FK3XsLBqC96SXZXNSwJL4Nx1gz45J3X0Q8RP9B9mWMFEA9nTc42aXN9lgXKKwJRGkxuGNuu2oCHkPa9meBPd6ksdJW0di7Nva/oWSPM4nUw6NK/M5uGZGd/I4kSVxpsjQM6dh1oNPEFtJ8jy079x0e6sGdnzqPGF96y04GGnJCCmVUaG6MEz2NpSj3CqL6/yZgkNA1WbDXCXDGNwaoaNH3kplxijFJbzRZVIyQ2bC+9jj5AM9fl44GSLWrZcZUgJtAT8KvZgKaJua3ud303T2HpFEeI9yIYj8E1ETFk02+oxe7XfyO0wxOmp1HDFnX4N6OrkpTWDts7oyWt95iTpKuViBaCakJaQEddgS3jHCwNSsq1FwcYAjdhqTt1aHvfYp+3NpBpqakI999cleYBbhKsUpK8WC3V8cQxaRlAOa/gruYrzuHU1QQndyZjFUXtRkIs7jw75MFKCD20brUE=
