language: java

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  - "$HOME/google-cloud-sdk"

services:
- docker

before_install:
  - openssl aes-256-cbc -k "$DECRYPT_KEY" -in secret-storage.json.enc -out secret-storage.json -d

install: skip

addons:
  sonarcloud:
    organization: piggyback

script:
- mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-location
- docker build -t piggy1/location .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push piggy1/location
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- mvn -Pprod clean verify
- docker build -t location-prod .
- docker tag location-prod gcr.io/absolute-text-251105/piggy1-location:v1
- cat secret-storage.json | docker login -u _json_key --password-stdin https://gcr.io
- docker push gcr.io/absolute-text-251105/piggy1-location:v1

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: Sj0NggTmdIUm8pswzS6HBM6U/TFR7zDjsA3tyafkGnKEVcU4JaeJVL9xw0xUwk07LD+VXxyPXqj78sjrfLNLYhr56m9agZfvv3NdiLpsFuAwkYATVPBKYHvIRm9Cb9DmCTUgmdb8Xb3y2BcdTUJaLsek0fXPZfZaL5yuGaNpE2csjj3DCWDsoPHXj/jSA/rLo1CY4TUIr+W1sYyvn4crs0qOBwp4gUAO/1LEoGiUcw6laOoowzx3k0MO4Y5dFLlrCZ7kl3pCBINLajppesGbLXlN5xKHB/zMsrsRXg4F32u34a08nqT6A/gpzP5TFOxuIlK2RvxRS8lhOsED7+dLU8hCEpV/ce3iCD4sBLdNe149scqtAHm3zINkkU9joD9FjFfunIG+9vFjVzU4Vcm1PrryMiVqJ2AbS3MI41+8TEftWDdCs9uZ2bDRkpOrg5yAlcl9UlkVyog+/yrR3VQJyBdDxKrroRvjfqs5XxXnd4f3n19L/xgWJQsh+U/huynUcT6+y1ish3PvT0FUjfZ3OGOythfXgLaJoL4QhdI/ySb5y1+1HP7ViakHu2EcjT5CwxdBUSTNZPhGwUXrcKD5et2IELJ58+EKnFwqaXnTIXoPRvr+9uhXsEOv80gtFnxy9hnOtNcO992kSD1wX3FDDTrhdpc+WWp7HSS8+RCyivw=
