language:
  java

sudo:
  true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/google-cloud-sdk

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in secret-storage.json.enc -out secret-storage.json -d

install:
  skip

addons:
  sonarcloud:
    organization: "piggyback"

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-location
  - docker build -t piggy1/location .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push piggy1/location
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - cat secret-storage.json | docker login -u _json_key --password-stdin https://gcr.io
  - mvn -Pprod clean verify
  - docker build -t location-prod .
  - docker tag location-prod gcr.io/absolute-text-251105/piggy1-location:v1
  - docker push gcr.io/absolute-text-251105/piggy1-location:v1

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
